Repository grafana/grafana-api-golang-client, pull requests merged in 2020-10, with the labels that each got.

#4 Chore: Lint with golangci-lint
  .golangci.toml
  client.go
  folder_permissions_test.go
  team.go
  teams_test.go
Labels: chore

#7 Drone: Add Jsonnet config
  .drone.jsonnet
  .drone.yml
Labels: chore

#6 Return team id when adding team
  team.go
  teams_test.go
Labels: enhancement

#8 Chore: Enable style check linter
  .golangci.toml
  admin.go
  alertnotification.go
  alertnotification_test.go
  dashboard.go
  dashboard_test.go
  datasource.go
  datasource_test.go
  folder.go
  folder_permissions.go
  folder_permissions_test.go
  folder_test.go
  org_users.go
  org_users_test.go
  orgs.go
  orgs_test.go
  playlist.go
  playlist_test.go
  team.go
  teams_test.go
  user.go
  user_test.go
Labels: chore

#10 Client: Re-design New
  admin_test.go
  alert_test.go
  alertnotification_test.go
  annotation_test.go
  client.go
  client_test.go
  dashboard_test.go
  datasource_test.go
  folder_permissions_test.go
  folder_test.go
  mock.go
  org_users_test.go
  orgs_test.go
  playlist_test.go
  teams_test.go
  user_test.go
Labels: enhancement

#11 Fix team preferences api url
  team.go
  teams_test.go
Labels: bug

#9 Add organization ID to client connection using header
  client.go
  client_test.go
Labels: pr/external

#15 Add Deprecation Notice to README
  README.md
Labels: chore
